# -*- coding: utf-8 -*-
"""ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3wdewAaaN7Uc3dQUAWegsLxa7RcejGA
"""

# Commented out IPython magic to ensure Python compatibility.

# importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline


# importing data by url
df = pd.read_csv(r"C:\Users\Acer\Desktop\dmv and ml\ML\DATASETS\Wine.csv")
df.head()


# feature extraction
X = df.iloc[:,:-1]
y = df.iloc[:,-1]


from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


# using KNN algorithm for classification
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)


# prediction
import time
start = time.time()
y_pred = knn.predict(X_test)
print(time.time()-start)
# it is taking time for the prediction is
# ==> 0.010015010833740234


# validation
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
# it is giving accuracy
# ==> 0.7222222222222222


# Centralizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)


# Transforming the data
from sklearn.decomposition import PCA
pca = PCA(n_components=2) #hyperparameter of pca set


# Transforming the data
from sklearn.decomposition import PCA
pca = PCA(n_components=2) #hyperparameter of pca set

# ✅ Added this missing line
y_pred_trf = knn.predict(X_test_trf)

# Validation
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_trf)
# it is giving accuracy of
# ==> 0.9515476190476191


#transforming to a 2D coordinate system
pca = PCA(n_components=2)
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)


import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter(x=X_train_trf[:,0],
                 y=X_train_trf[:,1],
                 color=y_train_trf,
                 color_discrete_sequence=px.colors.qualitative.G10
)
fig.show()


#transforming to a 3D coordinate system
pca = PCA(n_components=3)
X_train_trf = pca.fit_transform(X_train)


import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=X_train_trf[:,0], y=X_train_trf[:,1], z=X_train_trf[:,2], color=y_train_trf)
fig.update_layout(margin=dict(l=20, r=20, t=20, b=20),
                  paper_bgcolor="LightSteelBlue",
)
fig.show()
