# -*- coding: utf-8 -*-
"""ML3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cz_3y4e5Jpxeq5GP22vN4Knp4MnRomG
"""

# Step 1: Import libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split


# Step 2: Load the dataset
digits = datasets.load_digits()


print("Dataset shape:", digits.images.shape) # (1797, 8, 8)
print("Labels shape:", digits.target.shape) # (1797,)


# Step 3: Display first 5 images with labels
plt.figure(figsize=(8, 2))
for i in range(5):
    plt.subplot(1, 5, i + 1)
    plt.imshow(digits.images[i], cmap=plt.cm.gray_r, interpolation="nearest")
    plt.title(f"Label: {digits.target[i]}")
plt.show()


# Step 4: Preprocess - flatten images
n_samples = len(digits.images)
X = digits.images.reshape((n_samples, -1)) # (1797, 64)
y = digits.target


# Step 5: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)


# Step 6: Create and train SVM model
clf = svm.SVC(gamma=0.001, C=100)
print("\nTraining the model...")
clf.fit(X_train, y_train)
clf.fit(X_train, y_train)
print("Training completed!")
clf


X


# Step 7: Predictions
y_pred = clf.predict(X_test)


# Step 8: Model Evaluation
print("\nAccuracy:", metrics.accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", metrics.classification_report(y_test, y_pred))
print("Confusion Matrix:\n", metrics.confusion_matrix(y_test, y_pred))


# Step 9: Visualize some predictions
fig, axes = plt.subplots(2, 5, figsize=(10, 5))
for ax, image, prediction, label in zip(axes.ravel(), X_test, y_pred, y_test):
    ax.imshow(image.reshape(8, 8), cmap=plt.cm.gray_r, interpolation="nearest")
    ax.set_title(f"Pred: {prediction}\nTrue: {label}")
    ax.axis("off")
plt.show()


# Step 10: Test on a single image
print("\nTesting on one image...")
sample_image = X_test[0].reshape(1, -1) # reshape for model input
predicted_value = clf.predict(sample_image)
plt.imshow(X_test[0].reshape(8, 8), cmap=plt.cm.gray_r, interpolation="nearest")
plt.title(f"Predicted: {predicted_value[0]}")
plt.show()

