# -*- coding: utf-8 -*-
"""ML4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DA_J6XhTL42VFZR-YLPZIltRgxj0NSI
"""

#Step 1: Import Required Libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import seaborn as sns


#Step 2: Load Dataset
iris_df = sns.load_dataset("iris")


iris_df["species"].value_counts()


print("First 5 rows of dataset:")
print(iris_df.head())


#Step 3: Data Preprocessing
#Extract only numeric features (drop species).
X = iris_df.drop('species', axis=1)
#Standardize data (important for K-Means).
#Why Standardization?
# Features like petal length (~5 cm) and sepal width (~3 cm) are on different scales.
# K-Means is distance-based, so scaling ensures fair contribution of each feature.
# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X


from sklearn.datasets import make_blobs
X,y = make_blobs(n_samples = 500,n_features = 2,centers = 3,random_state = 23)
fig = plt.figure(0)
plt.grid(True)
plt.scatter(X[:,0],X[:,1])
plt.show()


#Step 4: Apply Elbow Method
#The Elbow Method helps decide the optimal k.
inertia = []
K = range(1, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)
# Plot the elbow graph
plt.figure(figsize=(8, 5))
plt.plot(K, inertia, 'bo-')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method For Optimal k')
plt.show()


#Step 5: Apply K-Means Clustering
kmeans = KMeans(n_clusters=3, random_state=42)
iris_df['Cluster'] = kmeans.fit_predict(X_scaled)
print("\nCluster labels added:")
print(iris_df.head())


#Step 6: Visualization of Clusters
#(Using first two features for better understanding)
plt.figure(figsize=(8, 5))
plt.scatter(X_scaled[:, 0], X_scaled[:, 1], c=iris_df['Cluster'], cmap='viridis', s=50)
plt.title("K-Means Clustering on Iris Dataset")
plt.xlabel("Sepal Length (Standardized)")
plt.ylabel("Sepal Width (Standardized)")
plt.show()


# Step 6: Visualization of Clusters (Using 1st and 3rd features)
plt.figure(figsize=(8, 5))
plt.scatter(
X_scaled[:, 0], X_scaled[:, 2], c=iris_df['Cluster'], cmap='viridis', s=50
# 1st feature (Sepal Length), 3rd feature (Petal Length)
)
plt.title("K-Means Clustering on Iris Dataset")
plt.xlabel("Sepal Length (Standardized)")
plt.ylabel("Petal Length (Standardized)")
plt.show()


# Step 6: Visualization of Clusters (Using 2nd and 3rd features)
plt.figure(figsize=(8, 5))
plt.scatter(
X_scaled[:, 1], X_scaled[:, 2], c=iris_df['Cluster'], cmap='viridis', s=50
# 2nd feature (Sepal Width), 3rd feature (Petal Length)
)
plt.title("K-Means Clustering on Iris Dataset")
plt.xlabel("Sepal Width (Standardized)")
plt.ylabel("Petal Length (Standardized)")
plt.show()

